### ISSUE TITLE
Projeto - Criar Logomarca

### ISSUE THREAD

**Issue by wylliams** [WikiFarma/Repositorio-WikiFarma#9]
Criar uma logomarca com identidade visual do projeto.

**Comment by MarcoUpe** [comment]
![wf](https://cloud.githubusercontent.com/assets/11846812/7763533/66827a0c-0018-11e5-8c45-f93b805d4f66.png)

**Comment by MarcoUpe** [comment]
Criação da Logomarca encerrado.
